import dedent from "dedent";
import fs from "node:fs";
import terser from "@rollup/plugin-terser";

/**
 * Rollup plugin that replaces a specified variable name with "filename:line_number".
 */
function injectFNameLineNo(variable_name) {
    return {
        name: "inject-fname-lineno",
        transform(code, id) {
            if (!code.includes(variable_name)) return null;
            const filename = id.split("/").pop();
            const replaced = code
                .split("\n")
                .map((line, idx) => line.replaceAll(variable_name, JSON.stringify(`${filename}:${idx + 1}`)));
            return { code: replaced.join("\n"), map: null };
        },
    };
}

/**
 * Rollup plugin that outputs the bookmarklet as bookmarks HTML file with a favicon that the user can import.
 */
function teeBookmarkletHtml({ icon, label, input, output } = {}) {
    return {
        name: "tee-bookmarklet-html",
        buildStart() {
            // Sanity check options.
            if (!icon) return this.error("No `icon` specified");
            if (!label) return this.error("No `label` specified");
            if (!input) return this.error("No `input` JS file specified");
            if (!output) return this.error("No `output` HTML file specified");
            // Sanity check icon file.
            try {
                fs.accessSync(icon, fs.constants.R_OK);
            } catch (err) {
                return this.error(`Cannot read icon file "${icon}": ${err}`);
            }
        },
        generateBundle(_, bundle) {
            const bundleForInput = bundle[input];
            if (!bundleForInput) return this.error(`Cannot find bundle for input file "${input}"`);
            // Build.
            const href = bundleForInput.code.trim();
            const date = Math.floor(Date.now() / 1000);
            const iconData = fs.readFileSync(icon).toString("base64");
            const iconHref = `data:image/png;base64,${iconData}`;
            const projectUrl = "https://github.com/Robpol86/bookmarklet-template";
            const commitSha = process.env.GITHUB_SHA || "";
            const html = dedent`
                <!DOCTYPE NETSCAPE-Bookmark-file-1>
                <!-- Generated by rollup-tee-bookmarklet-html from:
                    ${projectUrl}
                    ${commitSha} -->
                <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
                <TITLE>Bookmarks</TITLE>
                <H1>Bookmarks</H1>
                <DL><p>
                    <DT><A HREF="${href}" ADD_DATE="${date}" ICON="${iconHref}">${label}</A>
                </DL><p>
            `;
            // Write.
            this.emitFile({
                type: "asset",
                fileName: output,
                source: html,
            });
        },
    };
}

// Main rollup config.
export default {
    input: "src/entrypoint.mjs",
    output: {
        file: "dist/bookmarklet.js",
        format: "iife",
        name: "Bookmarklet",
    },
    plugins: [
        // Replace __FNAME_LINENO__ with "filename.mjs:123" for logging.
        injectFNameLineNo("__FNAME_LINENO__"),
        // Adjust these settings to reduce the size of the final bookmarklet.
        terser({
            compress: {
                defaults: true,
                side_effects: true,
                passes: 4,
                unsafe: true,
            },
            format: {
                braces: false,
            },
            mangle: true,
        }),
        // Escapes characters and adds the "javascript:" prefix so users can just copy/paste it into their bookmark manager.
        { renderChunk: (c) => ({ code: "javascript:" + encodeURIComponent(c) }) },
        // Also output to bookmarklet.html.
        teeBookmarkletHtml({
            icon: "icons/favicon.png",
            label: "Bookmarklet-Template",
            input: "bookmarklet.js",
            output: "bookmarklet.html",
        }),
    ],
};
